name: docker and application build

env: 
  DEV_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/felztrace-dev:latest
  RUNTIME_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/felztrace-runtime:latest

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'docker/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'docker/**'
      - '.github/workflows/build.yml'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect docker changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docker:
              - 'docker/**'
              - '.github/workflows/build.yml'
          
      - name: Log in to GitHub Container Registry
        if: steps.changes.outputs.docker == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: steps.changes.outputs.docker == 'true'
        run: docker build --target builder -t "$DEV_IMAGE_NAME" -f docker/Dockerfile .

      - name: Push image to GitHub Container Registry
        if: steps.changes.outputs.docker == 'true' && github.event_name == 'push'
        run: docker push "$DEV_IMAGE_NAME"

  build-app:
    needs: docker-build-and-push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: pull dev container
        run: |
          docker pull "$DEV_IMAGE_NAME"

      - name: check clang-format
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" /bin/bash -c "scripts/check-clang-format.sh"

      - name: build application
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" /bin/bash -c "scripts/build.sh --release --no-tests"

      - name: run tests
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" /bin/bash -c "ctest --test-dir build-release --output-on-failure"

      - name: run clang-tidy analysis
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" /bin/bash -c "cmake --build build-release --target clang-tidy"

      - name: run clang static analysis
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" /bin/bash -c "cmake --build build-release --target static-analyze"
      
      - name: run cppcheck analysis
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" /bin/bash -c "cmake --build build-release --target cppcheck"
      
      - name: coverage analysis
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: |
          docker run --rm --user $(id -u):$(id -g) -v "$PWD":/repository "$DEV_IMAGE_NAME" scripts/build.sh --coverage
      
      - name: upload coverage reports to artifacts
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            build-cov/*.html
            build-cov/*.css

      - name: upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: felztrace-binary
          path: build-release/FelzTrace

  build-and-push-runtime:
    needs: build-app
    if: success()
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: felztrace-binary
          path: build-release

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build runtime container
        run: docker build --target runtime -t "$RUNTIME_IMAGE_NAME" -f docker/Dockerfile .

      - name: Push runtime image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push "$RUNTIME_IMAGE_NAME"
